name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      # Installs system dependencies needed for playwright.
      - uses: microsoft/playwright-github-action@v1

      # Needed because a recent version of NPM changed SHAs for git
      # dependencies, breaking our package-lock.json files.
      - name: Update NPM
        run: npm i --global npm@^7.8.0

      - name: NPM install
        run: npm ci

      # https://github.com/npm/cli/issues/1905
      - name: NPM prepare (workaround)
        run: npm run prepare

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint
